[package]
name = "avatar"
version = "1.0.0"
edition = "2021"

[dependencies]
anyhow = "1.0.78"
axum = "0.7.3"
image = "0.24.7"
imageproc = "0.23.0"
rusttype = "0.9.3"
thiserror = "1.0.53"
tokio = { version = "1.35.1", features = ["rt-multi-thread", "macros"] }
